# Generated by Django 4.2.5 on 2023-10-08 22:45

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[users.validators.validate_domain], verbose_name='Адрес электронной почты'),
        ),
    ]
