# Generated by Django 4.2.5 on 2023-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_rub',
            field=models.PositiveIntegerField(default=0, verbose_name='Продажи без признака промо в руб.'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_rub_promo',
            field=models.PositiveIntegerField(default=0, verbose_name='Продажи с признаком промо в руб.'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_units',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число продаж без признака промо'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_units_promo',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число продаж с признаком промо'),
        ),
    ]
